name: MLB Web Updater

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 lxml playwright

      - name: Install Playwright Browsers (Firefox)
        run: |
          python -m playwright install firefox

      - name: Run Webcast Scraper
        run: |
          echo "Starting MLB Web updater..."
          python emelbe.py

      - name: Check if playlist files exist
        run: |
          if [ ! -f emelbecast_VLC.m3u8 ]; then
            echo "emelbecast_VLC.m3u8 not generated"
            exit 1
          fi
          if [ ! -f emelbebcast_TiviMate.m3u8 ]; then
            echo "emelbebcast_TiviMate.m3u8 not generated"
            exit 1
          fi

      - name: Commit and Push Updated Playlists
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add emelbebcast_TiviMate.m3u8 emelbebcast_TiviMate.m3u8

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "Committing updated playlist files..."
            git commit -m "Update MLB Web Playlists $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
